# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

autoload -Uz compinit && compinit
autoload -Uz vcs_info
precmd() { vcs_info }


#binds
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%b'

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST

PROMPT='[%n@%m %1~]%F{green}(${vcs_info_msg_0_})%F{white}$ '



#checks
aws --version &> /dev/null
if [ $? -ne 0 ]; then
    echo "AWS CLI is not installed. Please install it to use AWS commands."
fi


export PATH
